apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counting
  template:
    metadata:
      labels:
        app: counting
    spec:
      containers:
        - name: counting
          image: counting
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name