apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - name: statistics
          image: statistics
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name